### ISSUE TITLE
additional PDF generation libraries

### ISSUE THREAD

**Issue by masinter** [masinter/pdfrfc#18]
Leonard Rosenthal gave some pointers to software packages to investigate:

Commercial:
* Prince (<http://www.princexml.com/>) for HTML->PDF 
* The granddaddy of XSL:FO formatters is from AntennaHouse <http://www.antennahouse.com/>), 
*  RenderX (<http://www.renderx.com/>).  
* Adobe InDesign (and ID Server) 
* Adobe FrameMaker 

Open source: 
* a common alternative to FOP (for XSL:FO) is xmlroff <http://sourceforge.net/projects/xmlroff/>). 

There are numerous open source projects that can input either XML or HTML and output PDF. To name a few:

* iText (<http://itextpdf.com/>),
*  ReportLab (<http://www.reportlab.com/opensource/>), 
* wkhtmltopdf (<http://wkhtmltopdf.org/>), 
* xhtml2pdf(<http://www.xhtml2pdf.com/>) 
* HTMLDoc (<http://www.msweet.org/projects.php?Z1>)

**Comment by TonyLHansen** [comment]
LM TODO: add some more verbiage to Appendix B.3

**Comment by masinter** [comment]
similarly, this should turn into a Recommendation, that we (design team, RSE, IAOC) establish some criteria for evaluation of PDF libraries and generation tools, including cost, performance, reliability, ease of use, quality of the PDF files (standard compliant) and then systematically discover and test available tools. This list of software is then just an input to the discovery and evaluation process.

**Comment by TonyLHansen** [comment]
See #70 for resolution
