### ISSUE TITLE
Andrew Sullivan comment: explain why running headers are here and not in plaintext

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#25]
> §2.1.3: This format defnition is keeping the existing running headers
> even as the "plain text" version ditches them.  It'd be good to
> explain why one and not the other (in one of the documents, or perhaps both).

I don't believe that such a discussion belongs in this doc, but am not sure where such discussion should go.

**Comment by hlflanagan** [comment]
I think having as a statement of fact that we will not use running headers and footers in the PDF version is fine. Justification, if we have any at all, can be elsewhere.

**Comment by TonyLHansen** [comment]
hmmm, except that the PDF version has maintained the running headers and footers. Did you have mean your point without the "not"?

**Comment by hlflanagan** [comment]
Well, no. I think the point of the initial issue was that the plain-text will NOT do running headers, while the PDF says it will. HTML of course doesn't do running headers either, so that makes two of the three formats without running headers, and Andrew doesn't understand why we would make a decision to diverge like that.

**Comment by masinter** [comment]
the nature and style of running headers and footers are document design issues along with typeface design. The typeface, weight, color, placement, content of running headers and footers should be part of the overall page design. I think the RFC editor might contract with one or more professional document layout designers to provide sample layouts / styles.

Headers and footers can be marked in the PDF as not part of the running text for accessibility.

**Comment by TonyLHansen** [comment]
IMO, PDF is oriented towards print even more so than the other formats. 

Add text about "the short title should be used in the footer".

**Comment by TonyLHansen** [comment]
dupe of #35
