### ISSUE TITLE
Andrew Sullivan comment: change "page break" verb

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#26]
> §2.1.5: For whatever it's worth, I hate the neologism "page break" as
> a verb.  Surely this is just "do not break pages"?

ok, use "insert a page break" instead of using a verb "page break"

**Comment by masinter** [comment]
see comment on commit

**Comment by TonyLHansen** [comment]
in the comment for the commit, be certain to list the issue number ("#26"). That way the comments and commits are visible within the issue history as well.

if you think this issue is done now, please close it.

**Comment by masinter** [comment]
The update https://github.com/TonyLHansen/pdfrfc/commit/ffb1dbe307d3be5331dac7043687b9abfb92ce03 
had two changes. The first is good. The second one makes a bad sentence worse.
It is the last sentence line 336, and needs some punctuation or word order change.

Here's a possible rewrite:

However, inserting line breaks mid-word can be harmful when the word  is actually a sequence of characters representing a protocol element or protocol sequence.

**Comment by TonyLHansen** [comment]
+1

**Comment by TonyLHansen** [comment]
LM TODO: change the verbiage
