### ISSUE TITLE
Andrew Sullivan comment: strike word in 2.2.7 title

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#29]
> §2.2.7: "Embedded bitmap images (SVG sources, JPEGs, PNGs, etc) should be
>      embedded."
>
> This reads as a tautology, which I think means that it's not what was
> intended.  Maybe strike the first "Embedded"?

ok

**Comment by LRosenthal** [comment]
Please take me off your threads!!

**Comment by TonyLHansen** [comment]
@LRosenthal,You need to go to github.com/masinter/pdfrfc and stop watching the project. You're the one that added yourself to the list.
