### ISSUE TITLE
Andrew Sullivan comment: explain PDF/E more

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#31]
> §3: Apart from its location (see above), it's a little strange that
> there is no nod in the text as to why PDF/E is not right for the IETF.
> PDF/UA is called for but not explained in the text.

I suggest we add to the text something explaining PDF/E a little more, such as this sentence (paraphrased from the PDF/E FAQ):

   As PDF has evolved a broad set of capabilities, additional standards
   for PDF files are applicable.  These standards establish ground rules
   that are important for specific applications.  For example PDF/X was
   specifically designed for Prepress digital data exchange, with
   careful attention to color management and printing instructions.
   The PDF/E standard was designed for engineering documents and
   is used in dynamic workflows (where a document continues to be
   revised after publication) and allows interactive media (including
   animation and 3D).

**Comment by masinter** [comment]
I wonder if it is helpful to explain more about PDF/A1 PDF/A2 and PDF/A3 since they're different, and also explain how they work as profiles
(this could go in the PDF MIME type definition, perhaps)

**Comment by TonyLHansen** [comment]
Sure, that sounds worth doing. Anything to help people in making sense of the choices.

**Comment by TonyLHansen** [comment]
LM TODO: add verbiage about PDF/A1, /A2 and /A3.

**Comment by masinter** [comment]
Two additional standards families are important to the
RFC format, though: long term preservation (PDF/A), and user
	acessibility (PDF/UA). PDF/A has sub-profiles: PDF/A-1 
	(ISO 19005-1) for archivable use of PDF 1.4, PDF/A-2 
	(ISO 19005-2) for archivable use of PDF 1.7 (ISO 32000-1:2008),
	and PDF/A-3, for use of ISO 32000-1 with support for
        embedded files.
