### ISSUE TITLE
Andrew Sullivan comment: add ref to Apple Preview

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#32]
> §B.1 It's a little strange to see Adobe's software on the list and yet
> not Apple's Preview.

It can certainly be added.

**Comment by TonyLHansen** [comment]
Suggest something like:

Apple Preview
	      Apple Macintosh- and iOS-based platforms. PDF Viewer / Reader for
	      the supported platforms. Offers some editing capabilities on the 
	      Macintosh.

**Comment by TonyLHansen** [comment]
LM TODO: will come up with some verbiage

**Comment by masinter** [comment]
I'm tempted to remove the list of viewers; the situation is evolving too quickly. If it is going to be accurate and useful, and this section remains, we'll need more data. 
For most platforms (iOS, OS X, Windows, Android, ChromeOS, Kindle), for most browsers, PDF viewing is now built in, and a list of other tools you might load isn't so useful.

**Comment by masinter** [comment]
thinking about this more:  
I think we should Recommend that (RSE, design team, IAOC) should perform a quick survey by supplying some test PDF files and asking people to view them with their default settings, and report on their OS, Browser, file, results. This would get real data about which viewers work, display signatures, attachments, note PDF/A conformance, etc.  Then the list of viewers would reflect reality. Anything we write without gathering more data is just speculation.
