### ISSUE TITLE
Dave Thaler comment: add comment on A4

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#34]
> 1)      On the paper size issue, what is most commonly used in other international publishing
> contexts such as IEEE standards, ACM conference papers, etc.?  Stating some such precedents
> would help.

Anyone have input on this they can share?

**Comment by mrbhardy** [comment]
I can say that ISO uses A4 (probably unsurprisingly).  I think it is relatively easy to make the margins fit so that you can print onto both US Letter and A4 without scaling and without making the document look bad (as mentioned in the document).  Perhaps we could formalize those margins?

**Comment by TonyLHansen** [comment]
seems reasonable

**Comment by TonyLHansen** [comment]
dup of #57
