### ISSUE TITLE
Dave Thaler comment: add comment about pagination requirements

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#35]
> 2)      Section 2.1.5 is really a discussion around pagination requirements independent of which
> paginated format is being discussed.  That is, doesn’t it apply equally to the plaintext format,
> and any other (future) paginated format?   Seems like it should just be in one place and be referred
> to from other places.  Maybe it’s ok here if the plaintext doc adds a reference to here?

If plaintext were paginated, it would apply there as well. At the current time, it's not clear to me whether the plaintext form will be paginated or not. If it does wind up being paginated, then a pointer to here would probably be appropriate from the plaintext doc.

**Comment by hlflanagan** [comment]
It is paginated, but without running headers and footers. See Section 4 of draft-iab-rfc-plaintext.
"4.  General Page Format Layout

   One plain-text output will be created during the publication process
   with basic pagination that includes a form feed instruction every 58
   lines at most, including blank lines.  Instructions or a script will
   be made available by and for the community to strip out pagination as
   per individual preference"

**Comment by TonyLHansen** [comment]
TODO: move pagination info to separate appendix

**Comment by TonyLHansen** [comment]
sort of a dup of #42 but asking why we're doing pagination
