### ISSUE TITLE
Dave Thaler comment: move discussion on where hyperlinks to RFCs should point

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#36]
> 3)      Section 2.1.8 contains a discussion of where hyperlinks to RFCs should point.  I think this is
> a format-independent question and such discussion belongs in a non-format-specific document
> instead.

I agree. Design team, is there a better place for this comment to go?

**Comment by masinter** [comment]
if it moves, leave in a reference

**Comment by hlflanagan** [comment]
I think this will need to be addressed in the web portion of the Style Guide.

**Comment by TonyLHansen** [comment]
TLH TODO: change the links appropriately

**Comment by TonyLHansen** [comment]
this was done by adding a reference to the style guide RFC 7322
