### ISSUE TITLE
Dave Thaler comment: ss 2.1.2 on A4 use

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#39]
"A4 size by default"

What is most commonly used in other international publishing contexts such as IEEE standards, ACM conference papers, etc.?

**Comment by TonyLHansen** [comment]
if we leave as A4, we need more verbiate

**Comment by hlflanagan** [comment]
From what I could see, IEEE and ACM use US standard. I expect it depends on where in the world the SDO originates or calls 'home'.

**Comment by TonyLHansen** [comment]
dup of #57
