### ISSUE TITLE
More specific info on A4

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#66]
Dave Thaler comment:
See http://betweenborders.com/wordsmithing/a4-vs-us-letter/ for specific guidance on what the margins should be. In particular, use a bottom margin of 45mm in portrait mode.

**Comment by masinter** [comment]
RFC 2346 gives different advice

**Comment by TonyLHansen** [comment]
Add text such as:

Per RFC 2346, we should use A4 portrait mode with left and right margins of 20 mm, and top and bottom margins of 33 mm.
