### ISSUE TITLE
change text about I-D signatures

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#67]
Russ Housley comment:

>   Recommendation: At this time, the authors see no need for Internet-
>   Drafts to be signed with a PDF digital signature.
> 
> The IETF Secretariat currently signs all I-Ds.  See RFC 5485.
> 
> It seems to me that the decision to sign I-Ds should be left to the IESG and IETF Secretariat.  I suggest that this be removed from the document.
>

**Comment by masinter** [comment]
I don't agree -- I think the issue should be addressed in this document, and the alternatives laid out, even if the final decision is up to the IESG and IETF Secretariat.  

Note that Internet Drafts are currently signed using a separately served digital signature file, as described in RFC 5485.   PDF supports embedded digital signatures, and the question remains whether it is useful to sign Internet Drafts, using this facility.  Note there is an option to sign the embedded XML at the same time.

**Comment by hlflanagan** [comment]
Perhaps a compromise that states what is possible without the final recommendation by the authors that we don't sign PDF I-Ds? Or something that explicitly mentions the final decision on whether or not to do that is up to the IESG and the IETF Secretariat?

**Comment by TonyLHansen** [comment]
RFC 5485 is being updated by Russ. According to Russ, he thinks PDF I-Ds would likely use the internal signatures.

I suggest writing:

"The authors see no need for the PDF to be signed, but the final decision would rest with the IESG."

**Comment by hlflanagan** [comment]
I'm not entirely comfortable with that; if we're putting together a list of requirements, stating that this requirement is potentially problematic (displaying as it does a tension between authors and IESG), I think that reduces the overall clarity of the decisions documented in this draft.

**Comment by masinter** [comment]
The question is... what are the use cases for digital signatures of Internet Drafts and RFCs, and what are the requirements for signatures thereof, and are the requirements still served when the 'canonical' format is XML...  5485 signs the ASCII text. If you sign the XML do you also sign the PDF to insure a baseline agreement about presentation.

If RFC 5485 is being updated, we should put in an cross-reference to the update draft at least.

**Comment by hlflanagan** [comment]
RFC 5485 will be obsoleted by the draft Russ posted.

**Comment by TonyLHansen** [comment]
One of the reasons we put out internet drafts is to cause action to occur. This draft has been successful already in this regard for the use of PDF digital signatures. So, just like IANA considerations get rewritten as time goes along to reflect actions that have taken place instead of actions that need to take place, we can acknowledge that things have changed externally.

I just read Russ' update to RFC 5485. It says:

> 1. Introduction
>    For Internet-Drafts, the IETF Secretariat will generate the digital
>    signature shortly after the Internet-Draft is posted in the
>    repository.

> 2.  Detached Signature Files
> 
>    PDF files types accommodate embedded signatures, but other file
>    formats do not.  All other file types are digitally signed by
>    producing a detached signature file.

and

> 3.  Signed PDF Files
> 
>    PDF [PDF] has supported digital signatures since PDF 1.2, and the
>    signature covers the document content, the visual presentation, and
>    embedded content.  The RFC Editor plans to use this feature to have
>    the XML that was used to produce the PDF covered by the signature.
>    Authors of Internet-Drafts might do this as well, but they are not
>    required to do so.

This last sentence kind of confuses things a small bit. I guess he's covering the case where an author is allowed to upload the PDF version of the I-D themselves and it might include the author's signature in addition to the signature generated by the secretariat's tools.

I suggest we change

> Recommendation: At this time, the authors see no need for Internet-
> Drafts to be signed with a PDF digital signature.

to

> Recommendation: PDF versions of internet drafts will be signed by the IETF secretariat
> (<xref target='I-D.draft-housley-rfc-and-id-signatures'/>).

**Comment by hlflanagan** [comment]
That works for me.

**Comment by TonyLHansen** [comment]
Reading further on PDF signatures, I found that signatures can be set up in a way that will essentially lock the file from further modification, with variations. One tool offers these three options:

- No changes allowed: Signatures can be added, but no other changes are permitted.
- Fill in forms and digital signatures: Form fields can be completed and signatures added, but no other changes are permitted.
- Markups, fill in forms, and digital signatures: Markups can be added, form fields can be completed and signatures added, but no other changes are permitted.

(I'm not sure if the PDF spec offers other options.)

We need to mention this option within our text. 

For PDFs generated by the I-D upload tools from xml2rfc, I suggest that it be signed with no restrictions on what can be done to the document afterwards.

For PDFs uploaded by an individual, the signature being added should be set to the same as above. We should reject a PDF that would not allow the IETF Secretariat to resign it in that fashion.

For PDFs generated by the RFC Editor, it should be signed, certified and restrictions placed on it to only allow additional signatures and comments (markup) to be added.

**Comment by TonyLHansen** [comment]
some references for my previous comment (lmgtfy):
http://www.bluebeam.com/us/support/help/revu12/Content/RevuHelp/Signatures/Signing%20with%20Multiple%20Signatures.htm
https://helpx.adobe.com/acrobat/kb/certificate-signatures.html

**Comment by hlflanagan** [comment]
Have you talked with Russ about the potential revision to both this draft and the signing draft? We're coming to the end of the comment period and I'd like to make sure the open issues are wrapped up where possible.

**Comment by masinter** [comment]
There was a conversation with Russ but I'm not sure we came to a conclusion.
The right thing would be to change the text in this document to point to Russ's, but I haven't reviewed Russ' document carefully to write how it should read. I didn't see anything about legal standing and requirements by RSE and Secretariat for work proceeses. And I hope the opportunity to sign the PDF and (as an attachment) the XML used to create it, together, might help/

**Comment by TonyLHansen** [comment]
Remove the two recommendations in section 3.3, replacing them with:

The signing of Internet-Drafts and RFCs will be guided by draft-housley-rfc-and-id-signatures.

Recommendation: For PDFs generated by the I-D upload tools from xml2rfc, the authors suggest that it be signed with no restrictions on what can be done to the document afterwards. For PDFs uploaded by an individual, the signature being added should be set to the same as above. We should reject a PDF that would not allow the IETF Secretariat to resign it in that fashion. For PDFs generated by the RFC Editor, it should be signed, certified and restrictions placed on it to only allow additional signatures and comments (markup) to be added.
