### ISSUE TITLE
Joe Hildebrand comment about "lock down the visual presentation"

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#68]
Comment from Joe Hildebrand:

> 4- draft-iab-rfc-use-of-pdf, section 3.3, paragraph 1 says "but also to lock down the visual presentation 
> as well".  We're not sure if the current mechanism is going to do exactly that.  Can we either strike this
> clause or explore it with more text?

I'm not sure what he means by this.

**Comment by mrbhardy** [comment]
Well, I think he has a point, in that it is unclear what "lock down the visual presentation" means precisely.  A Digital Signature can be applied that allows a user to add comments after the fact or one that allows no changes at all.  I'd seen this wording before and didn't have a strong feeling against the wording, but his comment highlights to me that it isn't clear what we mean.

**Comment by TonyLHansen** [comment]
let's remove the sentence "The signature is intended ..."
