### ISSUE TITLE
<area> is wrong

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#69]
Julian Reschke comment:

> rfc2629.xslt warning:
> "WARNING: Unknown IETF area: "RFC Design Team" - should be one of:
> "Applications and Real-Time", "art", "General", "gen", "Internet",
> "int", "Operations and Management", "ops", "Routing", "rtg", "Security",
> "sec", "Transport", "tsv" (as of the publication date of 201601) (at
> line 60)"

This is correct. The doc says &lt;area&gt;RFC Design Team&lt;/area&gt;, which is not one of the names of an IETF area.

**Comment by masinter** [comment]
I suppose we should just take out <area>.

**Comment by TonyLHansen** [comment]
delete it
