### ISSUE TITLE
comments regarding appendix C.3 on PDF generators

### ISSUE THREAD

**Issue by TonyLHansen** [masinter/pdfrfc#70]
From Julian Reschke

> Appendix C.3:
>
> "One promising direction is suggested in
> <http://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html#output.pdf.fop>:
> using XSLT to generate XSL-FO which is then processed by a formatting
> object processor such as Apache FOP."
>
> It's not that promising, because:
>
> a) Generating XSL-FO from the XML source in addition to HTML duplicates
> a lot of code, causing lots of additional maintenance. I think it would
> be more promising to generate PDF from (X)HTML instead.
>
> b) XSL-FO itself is powerful, but Apache FOP lacks certain features
> which makes generating visually pleasing contents hard; notably the
> absence of table column balancing code. Other XSL-FO processors might be
> more powerful, but AFAIK none of this is open source.

I suggest that we just change the word "promising" to "possible". We _could_ add some of the above as further information, such as saying:

---

One possible direction is suggested in <http://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html#output.pdf.fop>: using XSLT to generate XSL-FO which is then processed by a formatting object processor such as Apache FOP. Some issues are that

- Apache FOP lacks certain features that would make it difficult to generate visually pleasing contents, such as table column balancing code.
- Other XML-FO processors that contain such features do not appear to be open source.

---

> Also, this should mention wkhtml, which is Webkit's HTML engine packaged
> as command line tool for printing/PDF generation.

I suggest adding something like this:

---

Another possible direction would use code common with the HTML generation and then use the Webkit HTML engine (wkhtml) to generate the final PDF.

---

**Comment by masinter** [comment]
I think this topic hides  an issue: there are multiple requirements:

- open source (Vs commercial)
- runs on multiple platforms (windows, mac, Linux)
- language/access (Java? Python? Server or command line)
- features (signatures? attachments? hyperlinks? page numbers in TOC?)
- quality of PDF generated (compressed? web serving)

And these are in conflict:  some PDF libraries meet some of these and not others.
The priorities for these may be different for I-D's and the RFC editor.

I think we shouldn't try to back-door the discussion of the priorities by discussing 'possible' implementations.

**Comment by TonyLHansen** [comment]
Then lets make the requirements more visible. Should there be a section in section 3 on Tooling Requirements?

Note: commercial is not necessarily out of the question for the RFC Production Center. But there should be an FOSS solution available that can be used by authors.

Multiple platforms has been stated for all tools that SoWs have been put out for.

Availability in various languages might influence the implementation.

Page numbers in TOC may or may not belong on this list. It's a requirement stated elsewhere and should not necessarily be affected by PDF generator selection.

**Comment by masinter** [comment]
what about a web service (like xml2rfc.tools.ietf.org) without a local implementation?
do people really need to generate PDF for their IDs when they're not online?

**Comment by TonyLHansen** [comment]
That is really a tooling requirements question. I'm thinking now that the answer needs to be decided somewhere other than our document.

**Comment by hlflanagan** [comment]
Agreed.

**Comment by TonyLHansen** [comment]
Add this sentence to Appendix C intro:

This list of software is input to the discovery and evaluation process. 

Add this to Appendix C.3:

"There are multiple requirements for tooling:

- open source (vs commercial)
- runs on multiple platforms (windows, mac, Linux)
- language/access (Java? Python? Server or command line)
- features (signatures? attachments? hyperlinks? page numbers in TOC?)
- quality of PDF generated (compressed? web serving)
- And these are in conflict: some PDF libraries meet some of these and not others.
- The priorities for these may be different for I-D's and the RFC editor."

Change "One promising" to "One possible".

Add the statement:

"Another possible direction would use code common with the HTML generation and then use the Webkit HTML engine (wkhtml) to generate the final PDF."

Move the sentence "(Some sample code illustrating how items can be attached to a PDF file and subsequently extracted can be found at <https://github.com/Aiybe/xmptest>.)" from section 3.2.7 to appendix C.3.

**Comment by masinter** [comment]
3.2.7 comment about Abe's library belongs in appendix C also
